In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
print(a)              
print(a.shape)

[1 2 3]
(3,)


In [5]:
print(np.array([1, 2, 3])   )           
print(np.zeros((2, 3)) )                 
print(np.ones((3, 2)))
print(np.arange(0, 10, 2)   )            
np.linspace(0, 1, 5)

[1 2 3]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 2 4 6 8]


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
a = np.arange(6)
print(a)
print(a.reshape((2, 3)))
print(a.ndim)
print(a.shape)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
1
(6,)


In [9]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a[0, 1],   
a[:, 1],      
a[1:3] )     

2 [2 4 6] [[3 4]
 [5 6]]


In [10]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print("a + b =", a + b)             
print("a * 2 =", a * 2)           
print("a ** 2 =", a ** 2)          
print("sqrt(a) =", np.sqrt(a))   

a + b = [11 22 33]
a * 2 = [2 4 6]
a ** 2 = [1 4 9]
sqrt(a) = [1.         1.41421356 1.73205081]


In [11]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.dot(a, b))
a @ b              

[[19 22]
 [43 50]]


array([[19, 22],
       [43, 50]])

In [12]:
a = np.array([5, 10, 15, 20])
a[a > 10]    


array([15, 20])

In [13]:
print(np.random.rand(2, 3))       
print(np.random.randint(1, 100))  
print(np.random.seed(42))          


[[0.53826346 0.47193073 0.02499026]
 [0.22731143 0.93250046 0.72909821]]
30
None


In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a.sum())          
print(a.mean())        
print(a.max(axis=0))     
a.min(axis=1)     


21
3.5
[4 5 6]


array([1, 4])